version: "1"
services:
    myapp:
        build:
            context: .
            dockerfile: Dockerfile
        image: tutapp
        ports:
            - "8090:8090"
        volumes:
            - ./src:/app/src
            - ./target:/app/target
